### ISSUE TITLE
请问config是最新的吗？

### ISSUE THREAD

**Issue by androidcn** [sooyaaabo/Loon#1]
谢谢

**Comment by sooyaaabo** [comment]
> 谢谢

并不是，只是自己备份用的，很久没更新了，参照的是可莉的最小配置
https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Config/Loon_Simple_Sample_Configuration_By_iKeLee.conf

**Comment by androidcn** [comment]
更新很及时
