### ISSUE TITLE
MyBlockAds与相关JD，TB，相冲突吗？

### ISSUE THREAD

**Issue by androidcn** [sooyaaabo/Loon#2]
只用大的插件
https://github.com/sooyaaabo/Loon/blob/main/plugins/MyBlockAds.plugin
就可以，还是可以继续添加相关插件？
是否会冲突与重复？

**Comment by sooyaaabo** [comment]
可以只用大的，如果你不需要其余的去广告就使用细分的，它是按照插件从上至下识别的，如果已经匹配到相应的域名去广告，就不会再向下查询匹配

**Comment by androidcn** [comment]
优秀👍
