### ISSUE TITLE
loon的配置文件能否提供一份非testflight的版本

### ISSUE THREAD

**Issue by zlkent** [sooyaaabo/Loon#3]
目前loon在appstore上的版本是3.2.2，配置文件适配的版本是testflight上的3.2.3，导入后会报错。虽然可以注释掉报错的两行，但不清楚会造成什么影响，所以希望能提供兼容正式版的配置文件。

**Comment by sooyaaabo** [comment]
上传了商店版的配置文件“Loon_Simple_Configuration_AppStore.conf”，把IP模式和asn数据库那两行注释掉即可，可以添加一行内容“ipv6=false”，您可以重新导入试试，应该不会报错（我没做测试），如果有问题，可以继续反馈，谢谢。
