### ISSUE TITLE
可以增加个花小猪去开屏广告吗

### ISSUE THREAD

**Issue by JimmyPOon1** [sooyaaabo/Loon#4]

**Comment by sooyaaabo** [comment]
抱歉，我只会转写格式，另外[广告拦截合集](https://raw.githubusercontent.com/sooyaaabo/Loon/main/Plugin/AdsBlocker.plugin)包含了`花小猪`，但我并不使用该软件，所以不知道是否去除了开屏，如有问题，可以向上游作者反馈。谢谢。

**Comment by sooyaaabo** [comment]
个人测试，开屏广告是过滤掉的，没有问题。

**Comment by JimmyPOon1** [comment]
我刚才清除缓存了确实可以 那请问中国电信有吗  我试了下不行呢

**Comment by sooyaaabo** [comment]
> 我刚才清除缓存了确实可以 那请问中国电信有吗 我试了下不行呢

中国电信不能MitM了
