### ISSUE TITLE
小红书和Bilibili插件路径更新

### ISSUE THREAD

**Issue by iflamma** [sooyaaabo/Loon#5]
商店版和测试版配置文件中

1. 
 https://raw.githubusercontent.com/sooyaaabo/Loon/main/Plugin/RedPaper.plugin 
**=>**
 https://raw.githubusercontent.com/sooyaaabo/Loon/main/Plugin/RedBook.plugin

2. 
 https://raw.githubusercontent.com/sooyaaabo/Loon/main/Plugin/BiliBili.plugin
 **=>** 
 https://raw.githubusercontent.com/sooyaaabo/Loon/main/Plugin/Bilibili.plugin

**Comment by sooyaaabo** [comment]
谢谢，已经注意到您说的问题，配置文件一般在app大版本更新时才会更新，已经提交新的commit。
