### ISSUE TITLE
又更了佬 你真勤快啊

### ISSUE THREAD

**Issue by liangfengquhe** [sooyaaabo/Loon#6]
酷 但是 我想问一下佬 规则的增加有什么好处吗 loon群里有人说 大量增加规则没有意义 因为loon
对同样的请求只会用一次规则

**Comment by sooyaaabo** [comment]
只要能达到你想要的效果就行，比如，google和github想要走不同地区就可以分开添加这两个规则分别指定，但如果没这个需求，就可以添加整合的国外网站规则就行，配置文件里只是适合我的，不一定适合你，自己调整就行，一般用blackmatrix7仓库内的规则
