### ISSUE TITLE
Nicegram插件失效

### ISSUE THREAD

**Issue by mxtao12345** [sooyaaabo/Loon#7]
显示没有开通会员~

**Comment by sooyaaabo** [comment]
抱歉，只负责搬运，转写为插件格式，不保证脚本有效性，如果失效，建议向上游作者反馈问题。另外，插件内写了操作流程图，可以再检查一下。本人不使用ng，所以不知道具体情况。

**Comment by mxtao12345** [comment]
好的好的，谢谢
